CREATE TABLE "VOL_PRO_SERVICE"."TestService"
(
 "ID" VARCHAR(36) NOT NULL,
 "DBNAME" VARCHAR(100) NOT NULL,
 "DBCONTENT" VARCHAR(100) NULL,
 "CREATEDATE" TIMESTAMP(3) NULL,
 "CREATEID" INT NULL,
 "CREATOR" VARCHAR(30) NULL,
 "MODIFIER" VARCHAR(30) NULL,
 "MODIFYDATE" TIMESTAMP(3) NULL,
 "MODIFYID" INT NULL,
   CONSTRAINT "PK__TESTSERV__3214EC077F60ED59"  CLUSTER PRIMARY KEY("ID") ENABLE 
);
INSERT INTO "VOL_PRO_SERVICE"."TestService"("ID","DBNAME","DBCONTENT","CREATEDATE","CREATEID","CREATOR","MODIFIER","MODIFYDATE","MODIFYID") VALUES('C0737155-AC39-4F35-87DC-22DD83896CAD','这是业务数据库','这是业务数据库。。',TO_DATE('2023-05-19 11:46:34.000','YYYY-MM-DD HH24:MI:SS.FF'),3362,'测试管理员',null,null,null);

ALTER TABLE "VOL_PRO_SERVICE"."TestService" ADD CONSTRAINT "PK__TESTSERV__3214EC077F60ED59" CLUSTER  PRIMARY KEY("ID") ;

