--导出序列

--DROP SEQUENCE "C##VOL_PRO_MAIN"."T_DEMO_CUSTOMER_SEQ";
CREATE SEQUENCE "C##VOL_PRO_MAIN"."T_DEMO_CUSTOMER_SEQ" MINVALUE 1000 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCACHE;

-- ----------------------------
-- Sequence structure for T_SYS_DICTIONARYLIST_SEQ
-- ----------------------------
--DROP SEQUENCE "C##VOL_PRO_MAIN"."T_SYS_DICTIONARYLIST_SEQ";
CREATE SEQUENCE "C##VOL_PRO_MAIN"."T_SYS_DICTIONARYLIST_SEQ" MINVALUE 1000 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCACHE;

-- ----------------------------
-- Sequence structure for T_SYS_DICTIONARY_SEQ
-- ----------------------------
--DROP SEQUENCE "C##VOL_PRO_MAIN"."T_SYS_DICTIONARY_SEQ";
CREATE SEQUENCE "C##VOL_PRO_MAIN"."T_SYS_DICTIONARY_SEQ" MINVALUE 1000 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCACHE;

-- ----------------------------
-- Sequence structure for T_SYS_LANGUAGE1_SEQ
-- ----------------------------
--DROP SEQUENCE "C##VOL_PRO_MAIN"."T_SYS_LANGUAGE1_SEQ";
CREATE SEQUENCE "C##VOL_PRO_MAIN"."T_SYS_LANGUAGE1_SEQ" MINVALUE 2000 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCACHE;

-- ----------------------------
-- Sequence structure for T_SYS_LANGUAGE_SEQ
-- ----------------------------
--DROP SEQUENCE "C##VOL_PRO_MAIN"."T_SYS_LANGUAGE_SEQ";
CREATE SEQUENCE "C##VOL_PRO_MAIN"."T_SYS_LANGUAGE_SEQ" MINVALUE 1000 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCACHE;

-- ----------------------------
-- Sequence structure for T_SYS_LOG1_SEQ
-- ----------------------------
--DROP SEQUENCE "C##VOL_PRO_MAIN"."T_SYS_LOG1_SEQ";
CREATE SEQUENCE "C##VOL_PRO_MAIN"."T_SYS_LOG1_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCACHE;

-- ----------------------------
-- Sequence structure for T_SYS_LOG_SEQ
-- ----------------------------
--DROP SEQUENCE "C##VOL_PRO_MAIN"."T_SYS_LOG_SEQ";
CREATE SEQUENCE "C##VOL_PRO_MAIN"."T_SYS_LOG_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCACHE;

-- ----------------------------
-- Sequence structure for T_SYS_MENU_SEQ
-- ----------------------------
--DROP SEQUENCE "C##VOL_PRO_MAIN"."T_SYS_MENU_SEQ";
CREATE SEQUENCE "C##VOL_PRO_MAIN"."T_SYS_MENU_SEQ" MINVALUE 1000 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCACHE;

-- ----------------------------
-- Sequence structure for T_SYS_ROLE_SEQ
-- ----------------------------
--DROP SEQUENCE "C##VOL_PRO_MAIN"."T_SYS_ROLE_SEQ";
CREATE SEQUENCE "C##VOL_PRO_MAIN"."T_SYS_ROLE_SEQ" MINVALUE 20 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCACHE;

-- ----------------------------
-- Sequence structure for T_SYS_TABLECOLUMN1_SEQ
-- ----------------------------
--DROP SEQUENCE "C##VOL_PRO_MAIN"."T_SYS_TABLECOLUMN1_SEQ";
CREATE SEQUENCE "C##VOL_PRO_MAIN"."T_SYS_TABLECOLUMN1_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCACHE;

-- ----------------------------
-- Sequence structure for T_SYS_TABLEINFO1_SEQ
-- ----------------------------
--DROP SEQUENCE "C##VOL_PRO_MAIN"."T_SYS_TABLEINFO1_SEQ";
CREATE SEQUENCE "C##VOL_PRO_MAIN"."T_SYS_TABLEINFO1_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCACHE;

-- ----------------------------
-- Sequence structure for T_SYS_TABLEINFO_SEQ
-- ----------------------------
--DROP SEQUENCE "C##VOL_PRO_MAIN"."T_SYS_TABLEINFO_SEQ";
CREATE SEQUENCE "C##VOL_PRO_MAIN"."T_SYS_TABLEINFO_SEQ" MINVALUE 9000 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCACHE;

-- ----------------------------
-- Sequence structure for T_SYS_USER_SEQ
-- ----------------------------
--DROP SEQUENCE "C##VOL_PRO_MAIN"."T_SYS_USER_SEQ";
CREATE SEQUENCE "C##VOL_PRO_MAIN"."T_SYS_USER_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCACHE;






--设置自增

CREATE TRIGGER "C##VOL_PRO_MAIN"."T_SYS_LOG_TRIGGER" BEFORE INSERT ON "C##VOL_PRO_MAIN"."SYS_LOG" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW WHEN (new.ID is null) 
begin
 select T_SYS_LOG_SEQ.nextval into:new.ID from dual;
 end;

 

CREATE TRIGGER "C##VOL_PRO_MAIN"."T_SYS_USER_TRIGGER" BEFORE INSERT ON "C##VOL_PRO_MAIN"."SYS_USER" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW WHEN (new.USER_ID is null) 
begin
 select T_SYS_USER_SEQ.nextval into:new.USER_ID from dual;
 end;


CREATE TRIGGER "C##VOL_PRO_MAIN"."T_SYS_ROLE_TRIGGER" BEFORE INSERT ON "C##VOL_PRO_MAIN"."SYS_ROLE" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW WHEN (new.ROLE_ID is null) 
begin
 select T_SYS_ROLE_SEQ.nextval into:new.ROLE_ID from dual;
 end;


CREATE TRIGGER "C##VOL_PRO_MAIN"."T_SYS_LANGUAGE_TRIGGER" BEFORE INSERT ON "C##VOL_PRO_MAIN"."SYS_LANGUAGE" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW WHEN (new.ID is null) 
begin
 select T_SYS_LANGUAGE_SEQ.nextval into:new.ID from dual;
 end;


CREATE TRIGGER "C##VOL_PRO_MAIN"."T_SYS_MENU_TRIGGER" BEFORE INSERT ON "C##VOL_PRO_MAIN"."SYS_MENU" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW WHEN (new.MENU_ID is null) 
begin
 select T_SYS_MENU_SEQ.nextval into:new.MENU_ID from dual;
 end;


CREATE TRIGGER "C##VOL_PRO_MAIN"."T_SYS_DICTIONARY_TRIGGER" BEFORE INSERT ON "C##VOL_PRO_MAIN"."SYS_DICTIONARY" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW WHEN (new.DIC_ID is null) 
begin
 select T_SYS_DICTIONARY_SEQ.nextval into:new.DIC_ID from dual;
 end;

CREATE TRIGGER "C##VOL_PRO_MAIN"."T_SYS_DICTIONARYLIST_TRIGGER" BEFORE INSERT ON "C##VOL_PRO_MAIN"."SYS_DICTIONARYLIST" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW WHEN (new.DICLIST_ID is null) 
begin
 select T_SYS_DICTIONARYLIST_SEQ.nextval into:new.DICLIST_ID from dual;
 end;

CREATE TRIGGER "C##VOL_PRO_MAIN"."T_DEMO_CUSTOMER_TRIGGER" BEFORE INSERT ON "C##VOL_PRO_MAIN"."DEMO_CUSTOMER" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW WHEN (new.CUSTOMER_ID is null) 
begin
 select T_DEMO_CUSTOMER_SEQ.nextval into:new.CUSTOMER_ID from dual;
 end;

CREATE SEQUENCE "C##VOL_PRO_MAIN"."T_SYS_ROLEAUTH_SEQ" MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 NOCACHE;

CREATE TRIGGER "C##VOL_PRO_MAIN"."T_SYS_ROLEAUTH_TRIGGER" BEFORE INSERT ON "C##VOL_PRO_MAIN"."SYS_ROLEAUTH" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW WHEN (new.AUTH_ID is null) 
begin
 select T_SYS_ROLEAUTH_SEQ.nextval into:new.AUTH_ID from dual;
 end;




CREATE TRIGGER "C##VOL_PRO_MAIN"."T_SYS_ROLEFIELDS_TRIGGER" BEFORE INSERT ON "C##VOL_PRO_MAIN"."SYS_ROLEFIELDS" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW WHEN (new.RoleFieldsId is null) 
begin
 select T_SYS_ROLEFIELDS_SEQ.nextval into:new.RoleFieldsId from dual;
 end;



CREATE TRIGGER "C##VOL_PRO_MAIN"."T_SYS_PRINTOPTIONS_TRIGGER" BEFORE INSERT ON "C##VOL_PRO_MAIN"."SYS_PRINTOPTIONS" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW WHEN (new.PRINTOPTIONSID is null) 
begin
 select T_SYS_PRINTOPTIONS_SEQ.nextval into:new.PRINTOPTIONSID from dual;
 end;



CREATE TRIGGER "C##VOL_PRO_MAIN"."T_SYS_TABLEINFO_TRIGGER" BEFORE INSERT ON "C##VOL_PRO_MAIN"."SYS_TABLEINFO" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW WHEN (new.TABLE_ID is null) 
begin
 select T_SYS_TABLEINFO_SEQ.nextval into:new.TABLE_ID from dual;
 end;



CREATE TRIGGER "C##VOL_PRO_MAIN"."T_SYS_TABLECOLUMN_TRIGGER" BEFORE INSERT ON "C##VOL_PRO_MAIN"."SYS_TABLECOLUMN" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW WHEN (new.COLUMNID is null) 
begin
 select T_SYS_TABLECOLUMN_SEQ.nextval into:new.COLUMNID from dual;
 end;